swagger: "2.0"
info:
  version: "1.0.0"
  title: "Order Service REST API"
paths:
  /orders:
    post:
      summary: "Создает новый заказ"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Заказ создан"
    get:
      summary: "Получает статус заказа"
